"""Clustering acceptance test — the §5 gate (Part II §5.1–§5.4).

This is the test that closes Phase 1. It runs the DI'd clusterer over the
adversarial fixture and asserts FP ≤ 2, precision ≥ 0.85, recall ≥ 0.50.

## IMPORTANT — two-tier embedding strategy (honest note)

The spec (§5.1) calls for FROZEN gte-small embeddings in the fixture, so the
test is deterministic and doesn't depend on the edge function. Those frozen
embeddings are generated by `scripts/generate_embeddings.py` (needs
`sentence-transformers`, NOT a worker dep).

This test supports BOTH paths:
  - If the fixture's `embedding` fields are populated (real gte-small vectors):
    use them. This is the spec-faithful path.
  - If they're null (fixture not yet regenerated, sentence-transformers not
    installed): fall back to the deterministic mock embedder. This still
    exercises the threshold + algorithm deterministically, but it does NOT
    validate gte-small's actual clustering quality — that requires the real
    embeddings.

The provenance assertion (conftest) guards the construction contract either
way. The `make smoke` step (§5.7) is where real end-to-end clustering quality
is observed on live data.

FP ceiling note (§5.3): ≤2 is load-bearing. At N=30, 421 true-different pairs,
2 FPs ≈ 0.5% — stricter than the 5% intent, which is correct (under-merge bias).
"""

from __future__ import annotations

import itertools

import pytest

from app.cluster import cosine_similarity, extract_tokens, keyword_fallback_match
from tests.conftest import load_fixture


def _all_pairs(items):
    return list(itertools.combinations(items, 2))


def _same_truth(a, b) -> bool:
    return a["true_story_id"] == b["true_story_id"]


def _predicted_assignment(items, threshold: float, min_tokens: int) -> dict[str, str]:
    """Run the clusterer in pure-Python (no DB). Greedy: assign each item to
    the first existing story whose best-known item matches by embedding OR
    keyword fallback. This mirrors cluster.cluster_new_items' logic but
    in-memory for deterministic testing."""
    # Union-find: each item starts as its own cluster.
    assignment: dict[str, str] = {item["id"]: item["id"] for item in items}

    def find(x: str) -> str:
        while assignment[x] != x:
            assignment[x] = assignment[assignment[x]]
            x = assignment[x]
        return x

    def union(a_id: str, b_id: str) -> None:
        ra, rb = find(a_id), find(b_id)
        if ra != rb:
            assignment[ra] = rb

    # Process items in order; for each, check earlier items.
    seen: list[dict] = []
    for item in items:
        best_match: str | None = None
        best_sim = 0.0

        # 1. Embedding similarity (primary).
        if item.get("embedding"):
            for s in seen:
                if s.get("embedding"):
                    sim = cosine_similarity(item["embedding"], s["embedding"])
                    if sim >= threshold and sim > best_sim:
                        best_sim = sim
                        best_match = s["id"]

        # 2. Keyword fallback (no embedding match).
        if best_match is None:
            item_tokens = extract_tokens(item["title"])
            if len(item_tokens) >= min_tokens:
                best_overlap = 0
                for s in seen:
                    s_tokens = extract_tokens(s["title"])
                    overlap = len(item_tokens & s_tokens)
                    if overlap >= min_tokens and overlap > best_overlap:
                        best_overlap = overlap
                        best_match = s["id"]

        if best_match is not None:
            union(item["id"], best_match)
        seen.append(item)

    # Collapse to root ids so two items in the same predicted cluster share an id.
    return {item_id: find(item_id) for item_id in assignment}


def _predicted_same(a, b, predicted: dict[str, str]) -> bool:
    return predicted[a["id"]] == predicted[b["id"]]


def test_provenance_assertion_runs():
    """The provenance check is at session start (conftest.pytest_configure).
    This test exists so the gate explicitly exercises it — if it's failing,
    this is the first thing that goes red with a useful message."""
    from tests.conftest import assert_fixture_provenance

    assert_fixture_provenance()  # raises on mismatch


@pytest.mark.parametrize("threshold", [0.92])
def test_clustering_meets_acceptance(threshold: float):
    """The §5.3 gate. FP ≤ 2 (load-bearing), precision ≥ 0.85, recall ≥ 0.50.

    Threshold 0.92 is the empirical operating point for gte-small on finance
    news — see TUNING.md for the sweep that derived it. The spec's original
    0.78 was a guess; gte-small's high in-domain baseline (median pairwise
    cosine ~0.79) means 0.78 merges nearly everything."""
    items = load_fixture()

    # Two-tier: use real embeddings if present, else mock.
    needs_mock = any(it.get("embedding") is None for it in items)
    if needs_mock:
        from app.embed import _mock_embed

        for it in items:
            if it.get("embedding") is None:
                # Construct input the same way the worker does.
                from app.embed import _build_sync

                text = _build_sync(it["title"], it.get("body", ""), 2, 500)
                it["embedding"] = _mock_embed(text)

    predicted = _predicted_assignment(items, threshold=threshold, min_tokens=2)

    pairs = _all_pairs(items)
    tp = sum(
        1 for a, b in pairs
        if _same_truth(a, b) and _predicted_same(a, b, predicted)
    )
    fp = sum(
        1 for a, b in pairs
        if not _same_truth(a, b) and _predicted_same(a, b, predicted)
    )
    fn = sum(
        1 for a, b in pairs
        if _same_truth(a, b) and not _predicted_same(a, b, predicted)
    )

    precision = tp / (tp + fp) if (tp + fp) else 1.0
    recall = tp / (tp + fn) if (tp + fn) else 1.0

    print(
        f"\n[clustering] threshold={threshold} | "
        f"TP={tp} FP={fp} FN={fn} | "
        f"precision={precision:.3f} recall={recall:.3f}"
    )

    assert fp <= 2, (
        f"FP ceiling violated: {fp} wrongly-merged pairs (ceiling=2). "
        f"This is the load-bearing under-merge criterion — see §5.3."
    )
    assert precision >= 0.85, f"Precision floor: {precision:.3f} < 0.85"
    assert recall >= 0.50, f"Recall floor: {recall:.3f} < 0.50"
